# Container do PHP
FROM php:8.1-fpm

RUN apt-get update && apt-get install -y \
    git \
    libzip-dev \
    unzip \
    libpq-dev \
    && docker-php-ext-install pdo pdo_mysql zip

# Pasta de trabalho
WORKDIR /var/www/html

# Copia o código-fonte do Laravel para dentro do container
COPY . .

# Instala as dependências do Composer
RUN curl -sS https://getcomposer.org/installer | /usr/local/bin/php -- --install-dir=/usr/local/bin --filename=composer
RUN /usr/local/bin/composer install --no-interaction

# Instala as dependências do NPM
# Instala o Node.js e o NPM
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y nodejs
RUN /usr/bin/npm install

# Copia o arquivo .env para dentro do container
COPY .env.example .env

# Gera a chave de aplicação do Laravel
RUN php artisan key:generate

# Expõe a porta do servidor web
EXPOSE 9000

# Inicia o servidor web do PHP
CMD ["php-fpm"]
